## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [33]:
# your code
# using boolean indexing 

arr = random.randint(10, size = 10)
print(arr)
arr[(arr > 3) & (arr < 8)] *= -1
print(arr) 

# using 'for' loop 

arr = random.randint(10, size = 10)
print(arr)
for i in range(len(arr)):
    if 3 < arr[i] < 8:
        arr[i] *= -1
print(arr) 

[1 4 0 0 4 6 0 5 3 2]
[ 1 -4  0  0 -4 -6  0 -5  3  2]
[2 6 1 4 3 3 6 9 6 9]
[ 2 -6  1 -4  3  3 -6  9 -6  9]


**2.** Заменить максимальный элемент случайного массива на 0

In [38]:
# your code
arr = random.randint(100, size = 10)
print(arr)

max_value = arr.max()
arr[arr == max_value] = 0
print(max_value)
print(arr)

[33 85 33 52 88 27 51 33 41 25]
88
[33 85 33 52  0 27 51 33 41 25]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [70]:
# your code
arr = random.randint(5, size = (2, 2), dtype = int)
print(arr)
cartesian_product = np.array(np.meshgrid(arr, arr)).T.reshape(-1,2)
print(cartesian_product)


[[2 0]
 [3 2]]
[[2 2]
 [2 0]
 [2 3]
 [2 2]
 [0 2]
 [0 0]
 [0 3]
 [0 2]
 [3 2]
 [3 0]
 [3 3]
 [3 2]
 [2 2]
 [2 0]
 [2 3]
 [2 2]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [90]:
# your code
A = random.randint(5, size = (8, 3), dtype = int)
B = random.randint(5, size = (2, 2), dtype = int)
print(A)
print(B)
matching_indices = []
for row in B:
    mask = np.array([np.all(np.isin(row, a)) for a in A])
    matching_rows = np.where(mask)[0]
    matching_indices.append(matching_rows)
print(matching_indices)

[[0 1 0]
 [0 4 1]
 [4 0 3]
 [3 2 2]
 [3 4 2]
 [1 1 4]
 [0 1 3]
 [3 3 2]]
[[4 2]
 [2 3]]
[array([4]), array([3, 4, 7])]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [96]:
# your code
arr = random.randint(3, size = (10, 3), dtype = int)
print(arr)
mask = np.array([len(np.unique(row)) > 1 for row in arr])
print(mask)
filtered_arr = arr[mask]
print(filtered_arr)

[[0 1 0]
 [1 1 1]
 [1 0 0]
 [0 0 0]
 [0 2 0]
 [0 0 1]
 [2 2 2]
 [0 2 1]
 [0 1 1]
 [1 0 1]]
[ True False  True False  True  True False  True  True  True]
[[0 1 0]
 [1 0 0]
 [0 2 0]
 [0 0 1]
 [0 2 1]
 [0 1 1]
 [1 0 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [100]:
# your code
arr = random.randint(2, size = (10, 3), dtype = int)
print(arr)
unique_arr = np.unique(arr, axis=0)
print(unique_arr)

[[0 1 0]
 [0 0 0]
 [1 0 0]
 [0 1 1]
 [1 0 1]
 [1 0 1]
 [0 0 1]
 [1 0 1]
 [0 0 1]
 [1 0 0]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [124]:
# your code
# without using numpy
X = [
    [1, 0, 1],
    [2, 0, 2],
    [3, 0, 3],
    [4, 4, 4]
]
def diagonal_product(matrix):
    product = 1
    for i in range(min(len(matrix), len(matrix[0]))):
        if matrix[i][i] != 0:
            product *= matrix[i][i]
    return product
print(diagonal_product(X))

# using numpy

X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
print(X)
product = np.prod(X[np.diag_indices(min(X.shape))][X[np.diag_indices(min(X.shape))] != 0])
print(product)

3
[[1 0 1]
 [2 0 2]
 [3 0 3]
 [4 4 4]]
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [119]:
# your code
# without using numpy
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
def equal_check(x, y):
    return sorted(x) == sorted(y)
print(equal_check(x, y))


# using numpy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
ux, cx = np.unique(x, return_counts=True)
uy, cy = np.unique(y, return_counts=True)

result = np.array_equal(ux, uy) & np.array_equal(cx, cy)
print(result)

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [134]:
# your code
# without using numpy

x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
elements_after_zero = []
for i in range(1, len(x)):
    if x[i - 1] == 0:
        elements_after_zero.append(x[i])
max_value = max(elements_after_zero) 
print("Elements after zero:", elements_after_zero)
print("Max value:", max_value)

# using numpy

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 
indices_of_elem_after_zeros = np.where(x[:-1] == 0)[0] + 1
print("Indices of elements after zero", indices_of_elem_after_zeros)
max_value = np.max(x[indices_of_elem_after_zeros])
print("Max value:", max_value)

Elements after zero: [3, 0, 5]
Max value: 5
Indices of elements after zero [3 5 6]
Max value: 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [140]:
# your code
# without using numpy

def run_length_encoding(lst):
    if not lst:
        return [], []

    values = [lst[0]]
    counts = [1]

    for i in range(1, len(lst)):
        if lst[i] == lst[i - 1]:
            counts[-1] += 1
        else:
            values.append(lst[i])
            counts.append(1)

    return values, counts

print(run_length_encoding([2, 2, 2, 3, 3, 3, 5]))

# using numpy

x = np.array([2, 2, 2, 3, 3, 3, 5])
print(np.unique(x, return_counts=True))

([2, 3, 5], [3, 3, 1])
(array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [167]:
# your code
# without using numpy

import math
import time
def euclidean_distance(x, y):
    return math.sqrt(sum((xi - yi) ** 2 for xi, yi in zip(x, y)))

X = [[1, 2], [3, 4], [5, 6]]
Y = [[1, 1], [4, 5]]

start_time = time.time()

distance_matrix = []
for x in X:
    row = []
    for y in Y:
        row.append(euclidean_distance(x, y))
    distance_matrix.append(row)

print("Euclidean distance matrix:")
for row in distance_matrix:
    print(row)

end_time = time.time()

print(f"Execution time in seconds: {end_time - start_time:.6f}")

# using numpy

import time

X = np.array([[1, 2], [3, 4], [5, 6]])
Y = np.array([[1, 1], [4, 5]])

start_time = time.time()
distance_matrix = np.sqrt(((X[:, np.newaxis, :] - Y[np.newaxis, :, :]) ** 2).sum(axis=2))
print("Euclidean distance matrix (with numpy):")
print(distance_matrix)

end_time = time.time()
print(f"Execution time with numpy in seconds: {end_time - start_time:.6f}")

# using scipy
from scipy.spatial.distance import cdist

X = np.array([[1, 2], [3, 4], [5, 6]])
Y = np.array([[1, 1], [4, 5]])

start_time = time.time()

print("Euclidean distance matrix (using scipy):")
print(cdist(X, Y))

end_time = time.time()
print(f"Execution time with scipy in seconds: {end_time - start_time:.6f}")

Euclidean distance matrix:
[1.0, 4.242640687119285]
[3.605551275463989, 1.4142135623730951]
[6.4031242374328485, 1.4142135623730951]
Execution time in seconds: 0.000252
Euclidean distance matrix (with numpy):
[[1.         4.24264069]
 [3.60555128 1.41421356]
 [6.40312424 1.41421356]]
Execution time with numpy in seconds: 0.000597
Euclidean distance matrix (using scipy):
[[1.         4.24264069]
 [3.60555128 1.41421356]
 [6.40312424 1.41421356]]
Execution time with scipy in seconds: 0.000238


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [173]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [182]:
calorie_stats = np.loadtxt(r"D:\Studying\DataAnalytics\Internship Innowise\python\cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [199]:
# your code
average_calories = np.mean(calorie_stats)
print(round(average_calories, 2))

106.88


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [184]:
# your code
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [185]:
# your code
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [191]:
# your code
percentiles = np.percentile(calorie_stats, np.arange(0, 101, 5))
print("Percentiles:", percentiles)

for p in range(0, 101, 5):
    value = np.percentile(calorie_stats, p)
    if value > 60:
        nth_percentile = p
        print(f"Lowest percentile above 60 calories: {nth_percentile}% ({value} calories)")
        break

Percentiles: [ 50.  70.  90.  90. 100. 100. 100. 100. 110. 110. 110. 110. 110. 110.
 110. 110. 120. 120. 124. 140. 160.]
Lowest percentile above 60 calories: 5% (70.0 calories)


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [195]:
# your code
more_calories = np.sum(calorie_stats > 60) / len(calorie_stats)
print(f"{more_calories:.2%}")

96.10%


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [198]:
# your code
calorie_std = np.std(calorie_stats)
print(round(calorie_std, 2))

19.36


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [213]:
# your code
print(f"""Анализ данных показал, что продукт компании намного низкокалорийнее по сравнению с продуктами конкурентов
и это можно использовать как продвижение продукта на рынке, выделяя это как преимущество среди других.

Так, можно оперировать данными и показывать, что продукт компании низкокалорийнее чем {more_calories:.2%} конкурентов, 
в то время как сам продукт компании имеет калорийность всего 60 Ккал, 
что на {round(average_calories - 60, 1)} Ккал ниже средней калорийности продуктов конкурентов, 
которая составляет {round(average_calories, 1)} Ккал """)

Анализ данных показал, что продукт компании намного низкокалорийнее по сравнению с продуктами конкурентов
и это можно использовать как продвижение продукта на рынке, выделяя это как преимущество среди других.

Так, можно оперировать данными и показывать, что продукт компании низкокалорийнее чем 96.10% конкурентов, 
в то время как сам продукт компании имеет калорийность всего 60 Ккал, 
что на 46.9 Ккал ниже средней калорийности продуктов конкурентов, 
которая составляет 106.9 Ккал 
